language: cpp

compiler: gcc

# Use cutting edge toolchains
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - boost1.55
    - gcc-6

# Build with all different supported toolchains
matrix:
  include:
    env:
      - BUILD_TYPE=Debug
      - BUILD_TYPE=Release
      - COMPILER=g++-7

# Build the binaries
script:
  - mkdir build
  - cd build
  - cmake .. && make -j 4